<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'white_october_breadcrumbs.helper' shared service.

return $this->services['white_october_breadcrumbs.helper'] = new \WhiteOctober\BreadcrumbsBundle\Templating\Helper\BreadcrumbsHelper(${($_ = isset($this->services['templating']) ? $this->services['templating'] : $this->load('getTemplatingService.php')) && false ?: '_'}, ${($_ = isset($this->services['white_october_breadcrumbs']) ? $this->services['white_october_breadcrumbs'] : $this->load('getWhiteOctoberBreadcrumbsService.php')) && false ?: '_'}, $this->parameters['white_october_breadcrumbs.options']);
