<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdx8ehz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdx8ehz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXdx8ehz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXdx8ehz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerXdx8ehz\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Xdx8ehz',
    'container.build_id' => '23f545a0',
    'container.build_time' => 1528213150,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdx8ehz');
