<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMyfrl7z\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMyfrl7z/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMyfrl7z.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMyfrl7z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerMyfrl7z\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Myfrl7z',
    'container.build_id' => '5783cf43',
    'container.build_time' => 1528208695,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMyfrl7z');
