<?php

namespace ex07Bundle\Repository;

/**
 * ex01Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ex07Repository extends \Doctrine\ORM\EntityRepository
{
}
