<?php

namespace ex05Bundle\Repository;

/**
 * ex01Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ex05Repository extends \Doctrine\ORM\EntityRepository
{
}
